version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter-api-express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./src:/app/src
    restart: unless-stopped
