version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter-api-express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key
      - MONGO_URI=mongodb://mongo:27017/flutter_ecommerce
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: flutter-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
